// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: proto/monitor/v1/monitor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextRequest) Reset() {
	*x = GetContextRequest{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextRequest) ProtoMessage() {}

func (x *GetContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextRequest.ProtoReflect.Descriptor instead.
func (*GetContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{0}
}

type ContextInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KubeContext   *string                `protobuf:"bytes,1,opt,name=kube_context,json=kubeContext,proto3,oneof" json:"kube_context,omitempty"`
	Cluster       *string                `protobuf:"bytes,2,opt,name=cluster,proto3,oneof" json:"cluster,omitempty"`
	GcloudProject *string                `protobuf:"bytes,3,opt,name=gcloud_project,json=gcloudProject,proto3,oneof" json:"gcloud_project,omitempty"`
	Contexts      []string               `protobuf:"bytes,4,rep,name=contexts,proto3" json:"contexts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextInfo) Reset() {
	*x = ContextInfo{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextInfo) ProtoMessage() {}

func (x *ContextInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextInfo.ProtoReflect.Descriptor instead.
func (*ContextInfo) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *ContextInfo) GetKubeContext() string {
	if x != nil && x.KubeContext != nil {
		return *x.KubeContext
	}
	return ""
}

func (x *ContextInfo) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *ContextInfo) GetGcloudProject() string {
	if x != nil && x.GcloudProject != nil {
		return *x.GcloudProject
	}
	return ""
}

func (x *ContextInfo) GetContexts() []string {
	if x != nil {
		return x.Contexts
	}
	return nil
}

type ListNamespacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesRequest) Reset() {
	*x = ListNamespacesRequest{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesRequest) ProtoMessage() {}

func (x *ListNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesRequest.ProtoReflect.Descriptor instead.
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *ListNamespacesRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type ListNamespacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []*NamespaceItem       `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesResponse) Reset() {
	*x = ListNamespacesResponse{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesResponse) ProtoMessage() {}

func (x *ListNamespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesResponse.ProtoReflect.Descriptor instead.
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *ListNamespacesResponse) GetNamespaces() []*NamespaceItem {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type NamespaceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceItem) Reset() {
	*x = NamespaceItem{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceItem) ProtoMessage() {}

func (x *NamespaceItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceItem.ProtoReflect.Descriptor instead.
func (*NamespaceItem) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *NamespaceItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListWorkloadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsRequest) Reset() {
	*x = ListWorkloadsRequest{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsRequest) ProtoMessage() {}

func (x *ListWorkloadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkloadsRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *ListWorkloadsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListWorkloadsRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type ListWorkloadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workloads     []*WorkloadItem        `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsResponse) Reset() {
	*x = ListWorkloadsResponse{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsResponse) ProtoMessage() {}

func (x *ListWorkloadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkloadsResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkloadsResponse) GetWorkloads() []*WorkloadItem {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type WorkloadItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Selector      map[string]string      `protobuf:"bytes,4,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadItem) Reset() {
	*x = WorkloadItem{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadItem) ProtoMessage() {}

func (x *WorkloadItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadItem.ProtoReflect.Descriptor instead.
func (*WorkloadItem) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *WorkloadItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorkloadItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadItem) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkloadItem) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	SinceMinutes  uint32                 `protobuf:"varint,5,opt,name=since_minutes,json=sinceMinutes,proto3" json:"since_minutes,omitempty"`
	StartTime     string                 `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Context       string                 `protobuf:"bytes,8,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{8}
}

func (x *GetLogsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetLogsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetLogsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetLogsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetLogsRequest) GetSinceMinutes() uint32 {
	if x != nil {
		return x.SinceMinutes
	}
	return 0
}

func (x *GetLogsRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetLogsRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetLogsRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{9}
}

func (x *GetLogsResponse) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp     *string                `protobuf:"bytes,3,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{10}
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return ""
}

type SearchLogsGlobalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	SinceMinutes  uint32                 `protobuf:"varint,3,opt,name=since_minutes,json=sinceMinutes,proto3" json:"since_minutes,omitempty"`
	Context       string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsGlobalRequest) Reset() {
	*x = SearchLogsGlobalRequest{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsGlobalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsGlobalRequest) ProtoMessage() {}

func (x *SearchLogsGlobalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsGlobalRequest.ProtoReflect.Descriptor instead.
func (*SearchLogsGlobalRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{11}
}

func (x *SearchLogsGlobalRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SearchLogsGlobalRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *SearchLogsGlobalRequest) GetSinceMinutes() uint32 {
	if x != nil {
		return x.SinceMinutes
	}
	return 0
}

func (x *SearchLogsGlobalRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type SearchLogsGlobalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*GlobalLogEntry      `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsGlobalResponse) Reset() {
	*x = SearchLogsGlobalResponse{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsGlobalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsGlobalResponse) ProtoMessage() {}

func (x *SearchLogsGlobalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsGlobalResponse.ProtoReflect.Descriptor instead.
func (*SearchLogsGlobalResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{12}
}

func (x *SearchLogsGlobalResponse) GetLogs() []*GlobalLogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

type GlobalLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadKind  string                 `protobuf:"bytes,1,opt,name=workload_kind,json=workloadKind,proto3" json:"workload_kind,omitempty"`
	WorkloadName  string                 `protobuf:"bytes,2,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Line          string                 `protobuf:"bytes,4,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp     *string                `protobuf:"bytes,5,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalLogEntry) Reset() {
	*x = GlobalLogEntry{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalLogEntry) ProtoMessage() {}

func (x *GlobalLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalLogEntry.ProtoReflect.Descriptor instead.
func (*GlobalLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{13}
}

func (x *GlobalLogEntry) GetWorkloadKind() string {
	if x != nil {
		return x.WorkloadKind
	}
	return ""
}

func (x *GlobalLogEntry) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *GlobalLogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GlobalLogEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *GlobalLogEntry) GetTimestamp() string {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return ""
}

type GetWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Context       string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadRequest) Reset() {
	*x = GetWorkloadRequest{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadRequest) ProtoMessage() {}

func (x *GetWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{14}
}

func (x *GetWorkloadRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetWorkloadRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetWorkloadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetWorkloadRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type GetEnvResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           []*EnvVar              `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvResponse) Reset() {
	*x = GetEnvResponse{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvResponse) ProtoMessage() {}

func (x *GetEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvResponse.ProtoReflect.Descriptor instead.
func (*GetEnvResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{15}
}

func (x *GetEnvResponse) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     string                 `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{16}
}

func (x *EnvVar) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *EnvVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetPodStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pods          []*PodStatusItem       `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodStatusResponse) Reset() {
	*x = GetPodStatusResponse{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodStatusResponse) ProtoMessage() {}

func (x *GetPodStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPodStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{17}
}

func (x *GetPodStatusResponse) GetPods() []*PodStatusItem {
	if x != nil {
		return x.Pods
	}
	return nil
}

type PodStatusItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Ready         string                 `protobuf:"bytes,3,opt,name=ready,proto3" json:"ready,omitempty"`
	Restarts      int32                  `protobuf:"varint,4,opt,name=restarts,proto3" json:"restarts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodStatusItem) Reset() {
	*x = PodStatusItem{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodStatusItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodStatusItem) ProtoMessage() {}

func (x *PodStatusItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodStatusItem.ProtoReflect.Descriptor instead.
func (*PodStatusItem) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{18}
}

func (x *PodStatusItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodStatusItem) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PodStatusItem) GetReady() string {
	if x != nil {
		return x.Ready
	}
	return ""
}

func (x *PodStatusItem) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

type PodTimeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*PodEvent            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodTimeline) Reset() {
	*x = PodTimeline{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodTimeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodTimeline) ProtoMessage() {}

func (x *PodTimeline) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodTimeline.ProtoReflect.Descriptor instead.
func (*PodTimeline) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{19}
}

func (x *PodTimeline) GetEvents() []*PodEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type PodEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Count         int32                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodEvent) Reset() {
	*x = PodEvent{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodEvent) ProtoMessage() {}

func (x *PodEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodEvent.ProtoReflect.Descriptor instead.
func (*PodEvent) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{20}
}

func (x *PodEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PodEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PodEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PodEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PodEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *PodEvent) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CrashDiagnostics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CrashDiagnostic     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrashDiagnostics) Reset() {
	*x = CrashDiagnostics{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrashDiagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrashDiagnostics) ProtoMessage() {}

func (x *CrashDiagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrashDiagnostics.ProtoReflect.Descriptor instead.
func (*CrashDiagnostics) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{21}
}

func (x *CrashDiagnostics) GetItems() []*CrashDiagnostic {
	if x != nil {
		return x.Items
	}
	return nil
}

type CrashDiagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pod           string                 `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	Container     string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Restarts      int32                  `protobuf:"varint,6,opt,name=restarts,proto3" json:"restarts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrashDiagnostic) Reset() {
	*x = CrashDiagnostic{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrashDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrashDiagnostic) ProtoMessage() {}

func (x *CrashDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrashDiagnostic.ProtoReflect.Descriptor instead.
func (*CrashDiagnostic) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{22}
}

func (x *CrashDiagnostic) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *CrashDiagnostic) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *CrashDiagnostic) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *CrashDiagnostic) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CrashDiagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CrashDiagnostic) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

type WorkloadMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items         []*ContainerMetric     `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadMetrics) Reset() {
	*x = WorkloadMetrics{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadMetrics) ProtoMessage() {}

func (x *WorkloadMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadMetrics.ProtoReflect.Descriptor instead.
func (*WorkloadMetrics) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{23}
}

func (x *WorkloadMetrics) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *WorkloadMetrics) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkloadMetrics) GetItems() []*ContainerMetric {
	if x != nil {
		return x.Items
	}
	return nil
}

type ContainerMetric struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pod              string                 `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	Container        string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	CpuUsageNano     int64                  `protobuf:"varint,3,opt,name=cpu_usage_nano,json=cpuUsageNano,proto3" json:"cpu_usage_nano,omitempty"`
	MemoryUsageBytes int64                  `protobuf:"varint,4,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContainerMetric) Reset() {
	*x = ContainerMetric{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMetric) ProtoMessage() {}

func (x *ContainerMetric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMetric.ProtoReflect.Descriptor instead.
func (*ContainerMetric) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{24}
}

func (x *ContainerMetric) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *ContainerMetric) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *ContainerMetric) GetCpuUsageNano() int64 {
	if x != nil {
		return x.CpuUsageNano
	}
	return 0
}

func (x *ContainerMetric) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

type WorkloadSpecItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Spec          *structpb.Struct       `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadSpecItem) Reset() {
	*x = WorkloadSpecItem{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSpecItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpecItem) ProtoMessage() {}

func (x *WorkloadSpecItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpecItem.ProtoReflect.Descriptor instead.
func (*WorkloadSpecItem) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{25}
}

func (x *WorkloadSpecItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorkloadSpecItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadSpecItem) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkloadSpecItem) GetSpec() *structpb.Struct {
	if x != nil {
		return x.Spec
	}
	return nil
}

type GetServiceMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceMapRequest) Reset() {
	*x = GetServiceMapRequest{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceMapRequest) ProtoMessage() {}

func (x *GetServiceMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceMapRequest.ProtoReflect.Descriptor instead.
func (*GetServiceMapRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{26}
}

func (x *GetServiceMapRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetServiceMapRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type ServiceMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*ServiceMapNode      `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*ServiceMapEdge      `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceMap) Reset() {
	*x = ServiceMap{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMap) ProtoMessage() {}

func (x *ServiceMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMap.ProtoReflect.Descriptor instead.
func (*ServiceMap) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{27}
}

func (x *ServiceMap) GetNodes() []*ServiceMapNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ServiceMap) GetEdges() []*ServiceMapEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type ServiceMapNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Health        string                 `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`
	TotalPods     int32                  `protobuf:"varint,5,opt,name=total_pods,json=totalPods,proto3" json:"total_pods,omitempty"`
	ReadyPods     int32                  `protobuf:"varint,6,opt,name=ready_pods,json=readyPods,proto3" json:"ready_pods,omitempty"`
	RestartCount  int32                  `protobuf:"varint,7,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceMapNode) Reset() {
	*x = ServiceMapNode{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMapNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMapNode) ProtoMessage() {}

func (x *ServiceMapNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMapNode.ProtoReflect.Descriptor instead.
func (*ServiceMapNode) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{28}
}

func (x *ServiceMapNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceMapNode) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ServiceMapNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceMapNode) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *ServiceMapNode) GetTotalPods() int32 {
	if x != nil {
		return x.TotalPods
	}
	return 0
}

func (x *ServiceMapNode) GetReadyPods() int32 {
	if x != nil {
		return x.ReadyPods
	}
	return 0
}

func (x *ServiceMapNode) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

type ServiceMapEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	EdgeType      string                 `protobuf:"bytes,3,opt,name=edge_type,json=edgeType,proto3" json:"edge_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceMapEdge) Reset() {
	*x = ServiceMapEdge{}
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMapEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMapEdge) ProtoMessage() {}

func (x *ServiceMapEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_v1_monitor_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMapEdge.ProtoReflect.Descriptor instead.
func (*ServiceMapEdge) Descriptor() ([]byte, []int) {
	return file_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{29}
}

func (x *ServiceMapEdge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ServiceMapEdge) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ServiceMapEdge) GetEdgeType() string {
	if x != nil {
		return x.EdgeType
	}
	return ""
}

var File_proto_monitor_v1_monitor_proto protoreflect.FileDescriptor

const file_proto_monitor_v1_monitor_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/monitor/v1/monitor.proto\x12\n" +
	"monitor.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x13\n" +
	"\x11GetContextRequest\"\xcc\x01\n" +
	"\vContextInfo\x12&\n" +
	"\fkube_context\x18\x01 \x01(\tH\x00R\vkubeContext\x88\x01\x01\x12\x1d\n" +
	"\acluster\x18\x02 \x01(\tH\x01R\acluster\x88\x01\x01\x12*\n" +
	"\x0egcloud_project\x18\x03 \x01(\tH\x02R\rgcloudProject\x88\x01\x01\x12\x1a\n" +
	"\bcontexts\x18\x04 \x03(\tR\bcontextsB\x0f\n" +
	"\r_kube_contextB\n" +
	"\n" +
	"\b_clusterB\x11\n" +
	"\x0f_gcloud_project\"1\n" +
	"\x15ListNamespacesRequest\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\"S\n" +
	"\x16ListNamespacesResponse\x129\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2\x19.monitor.v1.NamespaceItemR\n" +
	"namespaces\"#\n" +
	"\rNamespaceItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"N\n" +
	"\x14ListWorkloadsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\"O\n" +
	"\x15ListWorkloadsResponse\x126\n" +
	"\tworkloads\x18\x01 \x03(\v2\x18.monitor.v1.WorkloadItemR\tworkloads\"\xd5\x01\n" +
	"\fWorkloadItem\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12B\n" +
	"\bselector\x18\x04 \x03(\v2&.monitor.v1.WorkloadItem.SelectorEntryR\bselector\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x01\n" +
	"\x0eGetLogsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12#\n" +
	"\rsince_minutes\x18\x05 \x01(\rR\fsinceMinutes\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\tR\aendTime\x12\x18\n" +
	"\acontext\x18\b \x01(\tR\acontext\";\n" +
	"\x0fGetLogsResponse\x12(\n" +
	"\x04logs\x18\x01 \x03(\v2\x14.monitor.v1.LogEntryR\x04logs\"g\n" +
	"\bLogEntry\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12!\n" +
	"\ttimestamp\x18\x03 \x01(\tH\x00R\ttimestamp\x88\x01\x01B\f\n" +
	"\n" +
	"_timestamp\"\x8e\x01\n" +
	"\x17SearchLogsGlobalRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12#\n" +
	"\rsince_minutes\x18\x03 \x01(\rR\fsinceMinutes\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\"J\n" +
	"\x18SearchLogsGlobalResponse\x12.\n" +
	"\x04logs\x18\x01 \x03(\v2\x1a.monitor.v1.GlobalLogEntryR\x04logs\"\xb7\x01\n" +
	"\x0eGlobalLogEntry\x12#\n" +
	"\rworkload_kind\x18\x01 \x01(\tR\fworkloadKind\x12#\n" +
	"\rworkload_name\x18\x02 \x01(\tR\fworkloadName\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x12\n" +
	"\x04line\x18\x04 \x01(\tR\x04line\x12!\n" +
	"\ttimestamp\x18\x05 \x01(\tH\x00R\ttimestamp\x88\x01\x01B\f\n" +
	"\n" +
	"_timestamp\"t\n" +
	"\x12GetWorkloadRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\"6\n" +
	"\x0eGetEnvResponse\x12$\n" +
	"\x03env\x18\x01 \x03(\v2\x12.monitor.v1.EnvVarR\x03env\"P\n" +
	"\x06EnvVar\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainer\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"E\n" +
	"\x14GetPodStatusResponse\x12-\n" +
	"\x04pods\x18\x01 \x03(\v2\x19.monitor.v1.PodStatusItemR\x04pods\"k\n" +
	"\rPodStatusItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\tR\x05ready\x12\x1a\n" +
	"\brestarts\x18\x04 \x01(\x05R\brestarts\";\n" +
	"\vPodTimeline\x12,\n" +
	"\x06events\x18\x01 \x03(\v2\x14.monitor.v1.PodEventR\x06events\"\xa7\x01\n" +
	"\bPodEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x05R\x05count\"E\n" +
	"\x10CrashDiagnostics\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.monitor.v1.CrashDiagnosticR\x05items\"\xab\x01\n" +
	"\x0fCrashDiagnostic\x12\x10\n" +
	"\x03pod\x18\x01 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1a\n" +
	"\brestarts\x18\x06 \x01(\x05R\brestarts\"|\n" +
	"\x0fWorkloadMetrics\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x05items\x18\x03 \x03(\v2\x1b.monitor.v1.ContainerMetricR\x05items\"\x95\x01\n" +
	"\x0fContainerMetric\x12\x10\n" +
	"\x03pod\x18\x01 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\x12$\n" +
	"\x0ecpu_usage_nano\x18\x03 \x01(\x03R\fcpuUsageNano\x12,\n" +
	"\x12memory_usage_bytes\x18\x04 \x01(\x03R\x10memoryUsageBytes\"\x85\x01\n" +
	"\x10WorkloadSpecItem\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12+\n" +
	"\x04spec\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04spec\"N\n" +
	"\x14GetServiceMapRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\"p\n" +
	"\n" +
	"ServiceMap\x120\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1a.monitor.v1.ServiceMapNodeR\x05nodes\x120\n" +
	"\x05edges\x18\x02 \x03(\v2\x1a.monitor.v1.ServiceMapEdgeR\x05edges\"\xc3\x01\n" +
	"\x0eServiceMapNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06health\x18\x04 \x01(\tR\x06health\x12\x1d\n" +
	"\n" +
	"total_pods\x18\x05 \x01(\x05R\ttotalPods\x12\x1d\n" +
	"\n" +
	"ready_pods\x18\x06 \x01(\x05R\treadyPods\x12#\n" +
	"\rrestart_count\x18\a \x01(\x05R\frestartCount\"]\n" +
	"\x0eServiceMapEdge\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1b\n" +
	"\tedge_type\x18\x03 \x01(\tR\bedgeType2\x81\b\n" +
	"\x0eMonitorService\x12D\n" +
	"\n" +
	"GetContext\x12\x1d.monitor.v1.GetContextRequest\x1a\x17.monitor.v1.ContextInfo\x12W\n" +
	"\x0eListNamespaces\x12!.monitor.v1.ListNamespacesRequest\x1a\".monitor.v1.ListNamespacesResponse\x12T\n" +
	"\rListWorkloads\x12 .monitor.v1.ListWorkloadsRequest\x1a!.monitor.v1.ListWorkloadsResponse\x12B\n" +
	"\aGetLogs\x12\x1a.monitor.v1.GetLogsRequest\x1a\x1b.monitor.v1.GetLogsResponse\x12@\n" +
	"\n" +
	"StreamLogs\x12\x1a.monitor.v1.GetLogsRequest\x1a\x14.monitor.v1.LogEntry0\x01\x12]\n" +
	"\x10SearchLogsGlobal\x12#.monitor.v1.SearchLogsGlobalRequest\x1a$.monitor.v1.SearchLogsGlobalResponse\x12D\n" +
	"\x06GetEnv\x12\x1e.monitor.v1.GetWorkloadRequest\x1a\x1a.monitor.v1.GetEnvResponse\x12P\n" +
	"\fGetPodStatus\x12\x1e.monitor.v1.GetWorkloadRequest\x1a .monitor.v1.GetPodStatusResponse\x12O\n" +
	"\x0fGetWorkloadSpec\x12\x1e.monitor.v1.GetWorkloadRequest\x1a\x1c.monitor.v1.WorkloadSpecItem\x12I\n" +
	"\rGetServiceMap\x12 .monitor.v1.GetServiceMapRequest\x1a\x16.monitor.v1.ServiceMap\x12F\n" +
	"\vGetTimeline\x12\x1e.monitor.v1.GetWorkloadRequest\x1a\x17.monitor.v1.PodTimeline\x12N\n" +
	"\x0eGetDiagnostics\x12\x1e.monitor.v1.GetWorkloadRequest\x1a\x1c.monitor.v1.CrashDiagnostics\x12I\n" +
	"\n" +
	"GetMetrics\x12\x1e.monitor.v1.GetWorkloadRequest\x1a\x1b.monitor.v1.WorkloadMetricsB(Z&go-kube-monitor/backend/internal/pb;pbb\x06proto3"

var (
	file_proto_monitor_v1_monitor_proto_rawDescOnce sync.Once
	file_proto_monitor_v1_monitor_proto_rawDescData []byte
)

func file_proto_monitor_v1_monitor_proto_rawDescGZIP() []byte {
	file_proto_monitor_v1_monitor_proto_rawDescOnce.Do(func() {
		file_proto_monitor_v1_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_monitor_v1_monitor_proto_rawDesc), len(file_proto_monitor_v1_monitor_proto_rawDesc)))
	})
	return file_proto_monitor_v1_monitor_proto_rawDescData
}

var file_proto_monitor_v1_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_monitor_v1_monitor_proto_goTypes = []any{
	(*GetContextRequest)(nil),        // 0: monitor.v1.GetContextRequest
	(*ContextInfo)(nil),              // 1: monitor.v1.ContextInfo
	(*ListNamespacesRequest)(nil),    // 2: monitor.v1.ListNamespacesRequest
	(*ListNamespacesResponse)(nil),   // 3: monitor.v1.ListNamespacesResponse
	(*NamespaceItem)(nil),            // 4: monitor.v1.NamespaceItem
	(*ListWorkloadsRequest)(nil),     // 5: monitor.v1.ListWorkloadsRequest
	(*ListWorkloadsResponse)(nil),    // 6: monitor.v1.ListWorkloadsResponse
	(*WorkloadItem)(nil),             // 7: monitor.v1.WorkloadItem
	(*GetLogsRequest)(nil),           // 8: monitor.v1.GetLogsRequest
	(*GetLogsResponse)(nil),          // 9: monitor.v1.GetLogsResponse
	(*LogEntry)(nil),                 // 10: monitor.v1.LogEntry
	(*SearchLogsGlobalRequest)(nil),  // 11: monitor.v1.SearchLogsGlobalRequest
	(*SearchLogsGlobalResponse)(nil), // 12: monitor.v1.SearchLogsGlobalResponse
	(*GlobalLogEntry)(nil),           // 13: monitor.v1.GlobalLogEntry
	(*GetWorkloadRequest)(nil),       // 14: monitor.v1.GetWorkloadRequest
	(*GetEnvResponse)(nil),           // 15: monitor.v1.GetEnvResponse
	(*EnvVar)(nil),                   // 16: monitor.v1.EnvVar
	(*GetPodStatusResponse)(nil),     // 17: monitor.v1.GetPodStatusResponse
	(*PodStatusItem)(nil),            // 18: monitor.v1.PodStatusItem
	(*PodTimeline)(nil),              // 19: monitor.v1.PodTimeline
	(*PodEvent)(nil),                 // 20: monitor.v1.PodEvent
	(*CrashDiagnostics)(nil),         // 21: monitor.v1.CrashDiagnostics
	(*CrashDiagnostic)(nil),          // 22: monitor.v1.CrashDiagnostic
	(*WorkloadMetrics)(nil),          // 23: monitor.v1.WorkloadMetrics
	(*ContainerMetric)(nil),          // 24: monitor.v1.ContainerMetric
	(*WorkloadSpecItem)(nil),         // 25: monitor.v1.WorkloadSpecItem
	(*GetServiceMapRequest)(nil),     // 26: monitor.v1.GetServiceMapRequest
	(*ServiceMap)(nil),               // 27: monitor.v1.ServiceMap
	(*ServiceMapNode)(nil),           // 28: monitor.v1.ServiceMapNode
	(*ServiceMapEdge)(nil),           // 29: monitor.v1.ServiceMapEdge
	nil,                              // 30: monitor.v1.WorkloadItem.SelectorEntry
	(*structpb.Struct)(nil),          // 31: google.protobuf.Struct
}
var file_proto_monitor_v1_monitor_proto_depIdxs = []int32{
	4,  // 0: monitor.v1.ListNamespacesResponse.namespaces:type_name -> monitor.v1.NamespaceItem
	7,  // 1: monitor.v1.ListWorkloadsResponse.workloads:type_name -> monitor.v1.WorkloadItem
	30, // 2: monitor.v1.WorkloadItem.selector:type_name -> monitor.v1.WorkloadItem.SelectorEntry
	10, // 3: monitor.v1.GetLogsResponse.logs:type_name -> monitor.v1.LogEntry
	13, // 4: monitor.v1.SearchLogsGlobalResponse.logs:type_name -> monitor.v1.GlobalLogEntry
	16, // 5: monitor.v1.GetEnvResponse.env:type_name -> monitor.v1.EnvVar
	18, // 6: monitor.v1.GetPodStatusResponse.pods:type_name -> monitor.v1.PodStatusItem
	20, // 7: monitor.v1.PodTimeline.events:type_name -> monitor.v1.PodEvent
	22, // 8: monitor.v1.CrashDiagnostics.items:type_name -> monitor.v1.CrashDiagnostic
	24, // 9: monitor.v1.WorkloadMetrics.items:type_name -> monitor.v1.ContainerMetric
	31, // 10: monitor.v1.WorkloadSpecItem.spec:type_name -> google.protobuf.Struct
	28, // 11: monitor.v1.ServiceMap.nodes:type_name -> monitor.v1.ServiceMapNode
	29, // 12: monitor.v1.ServiceMap.edges:type_name -> monitor.v1.ServiceMapEdge
	0,  // 13: monitor.v1.MonitorService.GetContext:input_type -> monitor.v1.GetContextRequest
	2,  // 14: monitor.v1.MonitorService.ListNamespaces:input_type -> monitor.v1.ListNamespacesRequest
	5,  // 15: monitor.v1.MonitorService.ListWorkloads:input_type -> monitor.v1.ListWorkloadsRequest
	8,  // 16: monitor.v1.MonitorService.GetLogs:input_type -> monitor.v1.GetLogsRequest
	8,  // 17: monitor.v1.MonitorService.StreamLogs:input_type -> monitor.v1.GetLogsRequest
	11, // 18: monitor.v1.MonitorService.SearchLogsGlobal:input_type -> monitor.v1.SearchLogsGlobalRequest
	14, // 19: monitor.v1.MonitorService.GetEnv:input_type -> monitor.v1.GetWorkloadRequest
	14, // 20: monitor.v1.MonitorService.GetPodStatus:input_type -> monitor.v1.GetWorkloadRequest
	14, // 21: monitor.v1.MonitorService.GetWorkloadSpec:input_type -> monitor.v1.GetWorkloadRequest
	26, // 22: monitor.v1.MonitorService.GetServiceMap:input_type -> monitor.v1.GetServiceMapRequest
	14, // 23: monitor.v1.MonitorService.GetTimeline:input_type -> monitor.v1.GetWorkloadRequest
	14, // 24: monitor.v1.MonitorService.GetDiagnostics:input_type -> monitor.v1.GetWorkloadRequest
	14, // 25: monitor.v1.MonitorService.GetMetrics:input_type -> monitor.v1.GetWorkloadRequest
	1,  // 26: monitor.v1.MonitorService.GetContext:output_type -> monitor.v1.ContextInfo
	3,  // 27: monitor.v1.MonitorService.ListNamespaces:output_type -> monitor.v1.ListNamespacesResponse
	6,  // 28: monitor.v1.MonitorService.ListWorkloads:output_type -> monitor.v1.ListWorkloadsResponse
	9,  // 29: monitor.v1.MonitorService.GetLogs:output_type -> monitor.v1.GetLogsResponse
	10, // 30: monitor.v1.MonitorService.StreamLogs:output_type -> monitor.v1.LogEntry
	12, // 31: monitor.v1.MonitorService.SearchLogsGlobal:output_type -> monitor.v1.SearchLogsGlobalResponse
	15, // 32: monitor.v1.MonitorService.GetEnv:output_type -> monitor.v1.GetEnvResponse
	17, // 33: monitor.v1.MonitorService.GetPodStatus:output_type -> monitor.v1.GetPodStatusResponse
	25, // 34: monitor.v1.MonitorService.GetWorkloadSpec:output_type -> monitor.v1.WorkloadSpecItem
	27, // 35: monitor.v1.MonitorService.GetServiceMap:output_type -> monitor.v1.ServiceMap
	19, // 36: monitor.v1.MonitorService.GetTimeline:output_type -> monitor.v1.PodTimeline
	21, // 37: monitor.v1.MonitorService.GetDiagnostics:output_type -> monitor.v1.CrashDiagnostics
	23, // 38: monitor.v1.MonitorService.GetMetrics:output_type -> monitor.v1.WorkloadMetrics
	26, // [26:39] is the sub-list for method output_type
	13, // [13:26] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_monitor_v1_monitor_proto_init() }
func file_proto_monitor_v1_monitor_proto_init() {
	if File_proto_monitor_v1_monitor_proto != nil {
		return
	}
	file_proto_monitor_v1_monitor_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_monitor_v1_monitor_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_monitor_v1_monitor_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_monitor_v1_monitor_proto_rawDesc), len(file_proto_monitor_v1_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_monitor_v1_monitor_proto_goTypes,
		DependencyIndexes: file_proto_monitor_v1_monitor_proto_depIdxs,
		MessageInfos:      file_proto_monitor_v1_monitor_proto_msgTypes,
	}.Build()
	File_proto_monitor_v1_monitor_proto = out.File
	file_proto_monitor_v1_monitor_proto_goTypes = nil
	file_proto_monitor_v1_monitor_proto_depIdxs = nil
}
