// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: proto/monitor/v1/monitor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitorService_GetContext_FullMethodName       = "/monitor.v1.MonitorService/GetContext"
	MonitorService_ListNamespaces_FullMethodName   = "/monitor.v1.MonitorService/ListNamespaces"
	MonitorService_ListWorkloads_FullMethodName    = "/monitor.v1.MonitorService/ListWorkloads"
	MonitorService_GetLogs_FullMethodName          = "/monitor.v1.MonitorService/GetLogs"
	MonitorService_StreamLogs_FullMethodName       = "/monitor.v1.MonitorService/StreamLogs"
	MonitorService_SearchLogsGlobal_FullMethodName = "/monitor.v1.MonitorService/SearchLogsGlobal"
	MonitorService_GetEnv_FullMethodName           = "/monitor.v1.MonitorService/GetEnv"
	MonitorService_GetPodStatus_FullMethodName     = "/monitor.v1.MonitorService/GetPodStatus"
	MonitorService_GetWorkloadSpec_FullMethodName  = "/monitor.v1.MonitorService/GetWorkloadSpec"
	MonitorService_GetServiceMap_FullMethodName    = "/monitor.v1.MonitorService/GetServiceMap"
	MonitorService_GetTimeline_FullMethodName      = "/monitor.v1.MonitorService/GetTimeline"
	MonitorService_GetDiagnostics_FullMethodName   = "/monitor.v1.MonitorService/GetDiagnostics"
	MonitorService_GetMetrics_FullMethodName       = "/monitor.v1.MonitorService/GetMetrics"
)

// MonitorServiceClient is the client API for MonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitorServiceClient interface {
	GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*ContextInfo, error)
	ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error)
	ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error)
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error)
	StreamLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	SearchLogsGlobal(ctx context.Context, in *SearchLogsGlobalRequest, opts ...grpc.CallOption) (*SearchLogsGlobalResponse, error)
	GetEnv(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*GetEnvResponse, error)
	GetPodStatus(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*GetPodStatusResponse, error)
	GetWorkloadSpec(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*WorkloadSpecItem, error)
	GetServiceMap(ctx context.Context, in *GetServiceMapRequest, opts ...grpc.CallOption) (*ServiceMap, error)
	GetTimeline(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*PodTimeline, error)
	GetDiagnostics(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*CrashDiagnostics, error)
	GetMetrics(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*WorkloadMetrics, error)
}

type monitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorServiceClient(cc grpc.ClientConnInterface) MonitorServiceClient {
	return &monitorServiceClient{cc}
}

func (c *monitorServiceClient) GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*ContextInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextInfo)
	err := c.cc.Invoke(ctx, MonitorService_GetContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNamespacesResponse)
	err := c.cc.Invoke(ctx, MonitorService_ListNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkloadsResponse)
	err := c.cc.Invoke(ctx, MonitorService_ListWorkloads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogsResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) StreamLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MonitorService_ServiceDesc.Streams[0], MonitorService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitorService_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *monitorServiceClient) SearchLogsGlobal(ctx context.Context, in *SearchLogsGlobalRequest, opts ...grpc.CallOption) (*SearchLogsGlobalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchLogsGlobalResponse)
	err := c.cc.Invoke(ctx, MonitorService_SearchLogsGlobal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetEnv(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*GetEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnvResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetPodStatus(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*GetPodStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPodStatusResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetPodStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetWorkloadSpec(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*WorkloadSpecItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadSpecItem)
	err := c.cc.Invoke(ctx, MonitorService_GetWorkloadSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetServiceMap(ctx context.Context, in *GetServiceMapRequest, opts ...grpc.CallOption) (*ServiceMap, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceMap)
	err := c.cc.Invoke(ctx, MonitorService_GetServiceMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetTimeline(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*PodTimeline, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PodTimeline)
	err := c.cc.Invoke(ctx, MonitorService_GetTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetDiagnostics(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*CrashDiagnostics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrashDiagnostics)
	err := c.cc.Invoke(ctx, MonitorService_GetDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetMetrics(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*WorkloadMetrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadMetrics)
	err := c.cc.Invoke(ctx, MonitorService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServiceServer is the server API for MonitorService service.
// All implementations must embed UnimplementedMonitorServiceServer
// for forward compatibility.
type MonitorServiceServer interface {
	GetContext(context.Context, *GetContextRequest) (*ContextInfo, error)
	ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error)
	ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error)
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error)
	StreamLogs(*GetLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	SearchLogsGlobal(context.Context, *SearchLogsGlobalRequest) (*SearchLogsGlobalResponse, error)
	GetEnv(context.Context, *GetWorkloadRequest) (*GetEnvResponse, error)
	GetPodStatus(context.Context, *GetWorkloadRequest) (*GetPodStatusResponse, error)
	GetWorkloadSpec(context.Context, *GetWorkloadRequest) (*WorkloadSpecItem, error)
	GetServiceMap(context.Context, *GetServiceMapRequest) (*ServiceMap, error)
	GetTimeline(context.Context, *GetWorkloadRequest) (*PodTimeline, error)
	GetDiagnostics(context.Context, *GetWorkloadRequest) (*CrashDiagnostics, error)
	GetMetrics(context.Context, *GetWorkloadRequest) (*WorkloadMetrics, error)
	mustEmbedUnimplementedMonitorServiceServer()
}

// UnimplementedMonitorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitorServiceServer struct{}

func (UnimplementedMonitorServiceServer) GetContext(context.Context, *GetContextRequest) (*ContextInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContext not implemented")
}
func (UnimplementedMonitorServiceServer) ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedMonitorServiceServer) ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkloads not implemented")
}
func (UnimplementedMonitorServiceServer) GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedMonitorServiceServer) StreamLogs(*GetLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedMonitorServiceServer) SearchLogsGlobal(context.Context, *SearchLogsGlobalRequest) (*SearchLogsGlobalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchLogsGlobal not implemented")
}
func (UnimplementedMonitorServiceServer) GetEnv(context.Context, *GetWorkloadRequest) (*GetEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnv not implemented")
}
func (UnimplementedMonitorServiceServer) GetPodStatus(context.Context, *GetWorkloadRequest) (*GetPodStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodStatus not implemented")
}
func (UnimplementedMonitorServiceServer) GetWorkloadSpec(context.Context, *GetWorkloadRequest) (*WorkloadSpecItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkloadSpec not implemented")
}
func (UnimplementedMonitorServiceServer) GetServiceMap(context.Context, *GetServiceMapRequest) (*ServiceMap, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceMap not implemented")
}
func (UnimplementedMonitorServiceServer) GetTimeline(context.Context, *GetWorkloadRequest) (*PodTimeline, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeline not implemented")
}
func (UnimplementedMonitorServiceServer) GetDiagnostics(context.Context, *GetWorkloadRequest) (*CrashDiagnostics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiagnostics not implemented")
}
func (UnimplementedMonitorServiceServer) GetMetrics(context.Context, *GetWorkloadRequest) (*WorkloadMetrics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedMonitorServiceServer) mustEmbedUnimplementedMonitorServiceServer() {}
func (UnimplementedMonitorServiceServer) testEmbeddedByValue()                        {}

// UnsafeMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServiceServer will
// result in compilation errors.
type UnsafeMonitorServiceServer interface {
	mustEmbedUnimplementedMonitorServiceServer()
}

func RegisterMonitorServiceServer(s grpc.ServiceRegistrar, srv MonitorServiceServer) {
	// If the following call pancis, it indicates UnimplementedMonitorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitorService_ServiceDesc, srv)
}

func _MonitorService_GetContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetContext(ctx, req.(*GetContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamespacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_ListNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).ListNamespaces(ctx, req.(*ListNamespacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_ListWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkloadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).ListWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_ListWorkloads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).ListWorkloads(ctx, req.(*ListWorkloadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitorServiceServer).StreamLogs(m, &grpc.GenericServerStream[GetLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitorService_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

func _MonitorService_SearchLogsGlobal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchLogsGlobalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).SearchLogsGlobal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_SearchLogsGlobal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).SearchLogsGlobal(ctx, req.(*SearchLogsGlobalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetEnv(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetPodStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetPodStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetPodStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetPodStatus(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetWorkloadSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetWorkloadSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetWorkloadSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetWorkloadSpec(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetServiceMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetServiceMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetServiceMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetServiceMap(ctx, req.(*GetServiceMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetTimeline(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetDiagnostics(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetMetrics(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonitorService_ServiceDesc is the grpc.ServiceDesc for MonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.v1.MonitorService",
	HandlerType: (*MonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContext",
			Handler:    _MonitorService_GetContext_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _MonitorService_ListNamespaces_Handler,
		},
		{
			MethodName: "ListWorkloads",
			Handler:    _MonitorService_ListWorkloads_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _MonitorService_GetLogs_Handler,
		},
		{
			MethodName: "SearchLogsGlobal",
			Handler:    _MonitorService_SearchLogsGlobal_Handler,
		},
		{
			MethodName: "GetEnv",
			Handler:    _MonitorService_GetEnv_Handler,
		},
		{
			MethodName: "GetPodStatus",
			Handler:    _MonitorService_GetPodStatus_Handler,
		},
		{
			MethodName: "GetWorkloadSpec",
			Handler:    _MonitorService_GetWorkloadSpec_Handler,
		},
		{
			MethodName: "GetServiceMap",
			Handler:    _MonitorService_GetServiceMap_Handler,
		},
		{
			MethodName: "GetTimeline",
			Handler:    _MonitorService_GetTimeline_Handler,
		},
		{
			MethodName: "GetDiagnostics",
			Handler:    _MonitorService_GetDiagnostics_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _MonitorService_GetMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _MonitorService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/monitor/v1/monitor.proto",
}
